-- 1. Create students table
CREATE TABLE students (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nis VARCHAR(30) UNIQUE NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  class_name VARCHAR(30) NOT NULL,
  gender VARCHAR(10) CHECK (gender IN ('L', 'P')),
  qr_token UUID UNIQUE DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for searching
CREATE INDEX idx_students_class ON students(class_name);
CREATE INDEX idx_students_qr_token ON students(qr_token);

-- 2. Create prayer_logs table
CREATE TABLE prayer_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  prayer_type VARCHAR(10) NOT NULL CHECK (prayer_type IN ('zuhur', 'asar')),
  recorded_by UUID NOT NULL REFERENCES auth.users(id),
  prayer_date DATE NOT NULL DEFAULT CURRENT_DATE,
  scanned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT unique_student_prayer_daily UNIQUE (student_id, prayer_type, prayer_date)
);

-- Index for report queries performance
CREATE INDEX idx_prayer_logs_date ON prayer_logs(prayer_date);
CREATE INDEX idx_prayer_logs_student ON prayer_logs(student_id);
CREATE INDEX idx_prayer_logs_lookup ON prayer_logs(prayer_date, prayer_type);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE prayer_logs ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies for students table
-- Allow teachers (authenticated) to do everything
CREATE POLICY "Enable full access for authenticated users (teachers) on students" 
ON students FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);

-- Allow public (anon) to only select specific columns for the QR search page
-- Public can search student by name and class to retrieve qr_token
CREATE POLICY "Enable read access for all users on students" 
ON students FOR SELECT 
TO anon, authenticated
USING (true);

-- 5. Create Policies for prayer_logs table
-- Allow teachers (authenticated) to do everything
CREATE POLICY "Enable full access for authenticated users (teachers) on prayer_logs" 
ON prayer_logs FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);

-- Deny all access to prayer_logs for anonymous users
-- By default RLS is enabled and no policy means deny, but we can explicitly deny for clarity (not supported directly with TO anon USING false for INSERT/UPDATE)
-- But in Postgres, if no policy matches, it defaults to deny.
